name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASS }}
        docker build --build-arg MODEL_CIV=${{ vars.MODEL_CIV }} --build-arg LORAS=${{ vars.LORAS }} --build-arg CIV_KEY=${{ secrets.CIV_KEY }} -t lhexl/runpod-worker-comfy:dev --platform linux/amd64 .
        docker image push lhexl/runpod-worker-comfy:dev
      
