name: Docker Image CI
on:
  # позволяет запускать workflow вручную с вкладки actions в интерфейсе github.com
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: true
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASS }}
        docker build --build-arg CIV_KEY=${{ secrets.CIV_KEY }} -t lhexl/runpod-worker-comfy:pnrl --platform linux/amd64 .
        docker image push lhexl/runpod-worker-comfy:pnrl
      
